In [1]:
import os
import cv2
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import importlib
import datasets
import callbacks
import util
import profiler
from sklearn.model_selection import StratifiedShuffleSplit
from models import AlexNet

In [2]:
train_dataset, train_num = datasets.dogs_cats(init=False, training=True)

In [3]:
train_dataset = train_dataset.shuffle(train_num)

In [67]:
valid_num = int(train_num * 0.3)
train_data = train_dataset.skip(valid_num).shuffle(train_num - valid_num).batch(32).prefetch(1)
valid_data = train_dataset.take(valid_num).shuffle(valid_num).batch(32).prefetch(1)

In [68]:
importlib.reload(AlexNet)
model = AlexNet.AlexNet2()

input_test = tf.keras.Input(shape=(112,112,3))
model(input_test)
model.fit(train_data, validation_data=valid_data, epochs=2, verbose=2,
         callbacks=[callbacks.GetTensorboardCallback("../tensor_board/" + "layer_norm")])

Epoch 1/2
547/547 - 25s - loss: 435.0317 - sparse_categorical_accuracy: 0.5012 - val_loss: 6.9530 - val_sparse_categorical_accuracy: 0.5019
Epoch 2/2
547/547 - 21s - loss: 1.0842 - sparse_categorical_accuracy: 0.4997 - val_loss: 0.6957 - val_sparse_categorical_accuracy: 0.5013


In [5]:
profiler.profile_run("test()", "../profile_data/test3.prof")

In [6]:
a = tf.random.normal((2500, 112, 112, 3))
b = tf.zeros(2500,)

In [13]:
def test():
    for x, y in dataset:
        pass

In [14]:
profiler.profile_run("test()", "../profile_data/test3.prof")

In [7]:
profiler.profile_run("model.fit(a, b, validation_split=0.3, epochs=1, verbose=2, batch_size=8,\
         callbacks=[callbacks.GetTensorboardCallback('../tensor_board/' + 'layer_norm')])", "../profile_data/test2.prof")

219/219 - 8s - loss: 0.0029 - sparse_categorical_accuracy: 1.0000 - val_loss: 0.0000e+00 - val_sparse_categorical_accuracy: 1.0000 - 8s/epoch - 38ms/step


In [16]:
profiler.profile_run("model.fit(train_dataset, validation_data=valid_dataset, epochs=1, verbose=2,\
         callbacks=[callbacks.GetTensorboardCallback('../tensor_board/' + 'layer_norm')])", "../profile_data/test.prof")

157/157 - 173s - loss: 9351531.0000 - sparse_categorical_accuracy: 0.5160 - val_loss: 102.2935 - val_sparse_categorical_accuracy: 0.5000 - 173s/epoch - 1s/step


In [5]:
importlib.reload(AlexNet)
model = AlexNet.AlexNet2()
model.fit(train_dataset, validation_data=valid_dataset, epochs=1, verbose=2,
         callbacks=[callbacks.GetTensorboardCallback("../tensor_board/" + "layer_norm")])
# model.fit(a, b, validation_data=(c, d), epochs=100, batch_size=1)

157/157 - 228s - loss: 110.6713 - sparse_categorical_accuracy: 0.5080 - val_loss: 1.1275 - val_sparse_categorical_accuracy: 0.5120 - 228s/epoch - 1s/step


In [7]:

for x, y in test_dataset.batch(1):
    print(model(x))
    x = x[0, :, :, :].numpy()
    print(x.shape)
    cv2.imshow("img", x)
    cv2.waitKey(0)


tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)


KeyboardInterrupt: 

In [9]:
util.save_model(model, "../checkpoints/test_model.h5")

AttributeError: module 'util' has no attribute 'save_model'