In [26]:
import matplotlib.pyplot as plt

import datasets
import tensorflow as tf
from models import AlexNet

In [27]:
cifar_data = datasets.cifar100()
model = AlexNet.AlexNet100()

In [28]:
train_data = cifar_data[0]
train_label = cifar_data[1]
test_data = cifar_data[3]
test_label = cifar_data[4]
fine_name, coarse_name = cifar_data[6], cifar_data[7]

In [29]:
train_data.shape

(50000, 3072)

In [30]:
model.fit(train_data, train_label, validation_data=(test_data, test_label), epochs=1)

KeyboardInterrupt: 

In [1]:
import os
import cv2
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import importlib
import datasets
import callbacks
import util
import profiler
from sklearn.model_selection import StratifiedShuffleSplit
from models import AlexNet


In [2]:
dataset, data_len = datasets.dogs_cats(training=True)
test_dataset, test_len = datasets.dogs_cats(training=False)

In [3]:
dataset = dataset.shuffle(data_len)

In [15]:
# valid_size = int(data_len * 0.3)
# train_dataset = dataset.skip(valid_size).batch(8)
# valid_dataset = dataset.take(valid_size).batch(8)

valid_size = 1250
train_dataset = dataset.skip(valid_size).take(valid_size).batch(8)
valid_dataset = dataset.take(valid_size).batch(8)

In [5]:
importlib.reload(AlexNet)
model = AlexNet.AlexNet2()

In [6]:
a = tf.random.normal((2500, 112, 112, 3))
b = tf.zeros(2500,)

In [13]:
def test():
    for x, y in dataset:
        pass

In [14]:
profiler.profile_run("test()", "../profile_data/test3.prof")

In [7]:
profiler.profile_run("model.fit(a, b, validation_split=0.3, epochs=1, verbose=2, batch_size=8,\
         callbacks=[callbacks.GetTensorboardCallback('../tensor_board/' + 'layer_norm')])", "../profile_data/test2.prof")

219/219 - 8s - loss: 0.0029 - sparse_categorical_accuracy: 1.0000 - val_loss: 0.0000e+00 - val_sparse_categorical_accuracy: 1.0000 - 8s/epoch - 38ms/step


In [16]:
profiler.profile_run("model.fit(train_dataset, validation_data=valid_dataset, epochs=1, verbose=2,\
         callbacks=[callbacks.GetTensorboardCallback('../tensor_board/' + 'layer_norm')])", "../profile_data/test.prof")

157/157 - 173s - loss: 9351531.0000 - sparse_categorical_accuracy: 0.5160 - val_loss: 102.2935 - val_sparse_categorical_accuracy: 0.5000 - 173s/epoch - 1s/step


In [5]:
importlib.reload(AlexNet)
model = AlexNet.AlexNet2()
model.fit(train_dataset, validation_data=valid_dataset, epochs=1, verbose=2,
         callbacks=[callbacks.GetTensorboardCallback("../tensor_board/" + "layer_norm")])
# model.fit(a, b, validation_data=(c, d), epochs=100, batch_size=1)

2188/2188 - 301s - loss: 41.4704 - sparse_categorical_accuracy: 0.5001 - val_loss: 0.7069 - val_sparse_categorical_accuracy: 0.5072 - 301s/epoch - 138ms/step


In [7]:

for x, y in test_dataset.batch(1):
    print(model(x))
    x = x[0, :, :, :].numpy()
    print(x.shape)
    cv2.imshow("img", x)
    cv2.waitKey(0)


tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)


KeyboardInterrupt: 

In [9]:
util.save_model(model, "../checkpoints/test_model.h5")

AttributeError: module 'util' has no attribute 'save_model'