In [26]:
import matplotlib.pyplot as plt

import datasets
import tensorflow as tf
from models import AlexNet

In [27]:
cifar_data = datasets.cifar100()
model = AlexNet.AlexNet100()

In [28]:
train_data = cifar_data[0]
train_label = cifar_data[1]
test_data = cifar_data[3]
test_label = cifar_data[4]
fine_name, coarse_name = cifar_data[6], cifar_data[7]

In [29]:
train_data.shape

(50000, 3072)

In [30]:
model.fit(train_data, train_label, validation_data=(test_data, test_label), epochs=1)

KeyboardInterrupt: 

In [1]:
import os
import cv2
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import importlib
import datasets
import callbacks
import util
from sklearn.model_selection import StratifiedShuffleSplit
from models import AlexNet

In [2]:
importlib.reload(datasets)

<module 'datasets' from 'D:\\PycharmProjects\\AI_github\\src\\datasets.py'>

In [3]:
dataset, data_len = datasets.dogs_cats(training=True)
test_dataset, test_len = datasets.dogs_cats(training=False)

In [4]:
dataset = dataset.shuffle(data_len).batch(32)

In [5]:
valid_size = int(data_len * 0.3)
train_dataset = dataset.skip(valid_size)
valid_dataset = dataset.take(valid_size)

In [10]:
# split = StratifiedShuffleSplit(n_splits=1, test_size=0.3, random_state=1234)
# train_idx, valid_idx = next(split.split(train_data, train_label))
# train_image, valid_image = train_data[train_idx], train_data[valid_idx]
# train_answer, valid_answer = train_label[train_idx], train_label[valid_idx]

In [11]:
a = tf.random.normal((100, 112, 112, 3))
b = tf.zeros((100,))
c = tf.random.normal((100, 112, 112, 3))
d = tf.zeros((100,))

In [6]:
from cProfile import Profile

model = AlexNet.AlexNet2()
profiler = Profile()
profiler = profiler.run('model.fit(train_dataset, validation_data=valid_dataset, epochs=1, verbose=2,\
         callbacks=[callbacks.GetTensorboardCallback("../tensor_board/" + "layer_norm")])')

ValueError: Unexpected result of `train_function` (Empty logs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.

In [7]:
from pstats import Stats

stats = Stats(profiler)
stats.strip_dirs()
stats.sort_stats('cumulative')
stats.print_stats()

         2931864 function calls (2775024 primitive calls) in 77.294 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      5/1    0.000    0.000   77.297   77.297 {built-in method builtins.exec}
        1    0.000    0.000   77.297   77.297 <string>:1(<module>)
     67/1    0.000    0.000   77.297   77.297 traceback_utils.py:58(error_handler)
        1    0.000    0.000   77.297   77.297 training.py:1069(fit)
   2692/8    0.005    0.000   77.245    9.656 traceback_utils.py:138(error_handler)
        1    0.000    0.000   77.244   77.244 def_function.py:887(__call__)
        1    0.000    0.000   77.244   77.244 def_function.py:934(_call)
        1    0.000    0.000   76.085   76.085 function.py:2951(__call__)
        1    0.000    0.000   75.621   75.621 function.py:1782(_call_flat)
        1    0.000    0.000   75.620   75.620 function.py:454(call)
        1    0.000    0.000   75.220   75.220 execute.py:29(quick_execute)

In [12]:
importlib.reload(AlexNet)
model = AlexNet.AlexNet2()
model.fit(train_dataset, validation_data=valid_dataset, epochs=1, verbose=2,
         callbacks=[callbacks.GetTensorboardCallback("../tensor_board/" + "layer_norm")])
# model.fit(a, b, validation_data=(c, d), epochs=100, batch_size=1)

ValueError: Unexpected result of `train_function` (Empty logs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.

In [7]:

for x, y in test_dataset.batch(1):
    print(model(x))
    x = x[0, :, :, :].numpy()
    print(x.shape)
    cv2.imshow("img", x)
    cv2.waitKey(0)


tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)
tf.Tensor([[0. 1.]], shape=(1, 2), dtype=float32)
(112, 112, 3)


KeyboardInterrupt: 

In [9]:
util.save_model(model, "../checkpoints/test_model.h5")

AttributeError: module 'util' has no attribute 'save_model'